<?php

namespace Application\Controllers;

use Application\Core\User;
use Phalcon\Mvc\View;

class IndexController extends ControllerBase {
	public function beforeExecuteRoute($dispatcher)
    {
        parent::beforeExecuteRoute($dispatcher); // TODO: Change the autogenerated stub
    }

    public function indexAction() {
        $this->view->render('index','index');
//        echo "Hello Worlde";
    }

//    public function helloWorldAction() {
//        echo $this->view->render('index');
//		echo "Hello Worlde";
//	}
}

